I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/script.rpy", line 676, in script call
    call start2 from script2
  File "game/script2.rpy", line 417, in script call
    call battle
  File "game/battleEngine/test_battle.rpy", line 10, in script
    $ player = [player1]
  File "game/battleEngine/test_battle.rpy", line 10, in <module>
    $ player = [player1]
NameError: name 'player1' is not defined

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/script.rpy", line 676, in script call
    call start2 from script2
  File "game/script2.rpy", line 417, in script call
    call battle
  File "game/battleEngine/test_battle.rpy", line 10, in script
    $ player = [player1]
  File "D:\Downloads\renpy-7.3.5-sdk\renpy\ast.py", line 914, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Downloads\renpy-7.3.5-sdk\renpy\python.py", line 2028, in py_exec_bytecode
    exec bytecode in globals, locals
  File "game/battleEngine/test_battle.rpy", line 10, in <module>
    $ player = [player1]
NameError: name 'player1' is not defined

Windows-8-6.2.9200
Ren'Py 7.3.5.606
MythJam2020 1.0
Sun Oct 11 02:45:23 2020
